# .github/workflows/main.yml
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: 安装JavaFX
        run: |
          sudo apt-get update
          sudo apt-get install -y openjfx
      - name: 设置JAVAFX_HOME环境变量
        run: echo "JAVAFX_HOME=/usr/share/openjfx" >> $GITHUB_ENV
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
